# -*- coding: utf-8 -*-
#
# Copyright (C) 2024 CESNET.
#
# OARepo ecosystem is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#
# This file was automatically generated by the integration tests to show which changes
# were applied to the package.
"""Changes performed by oarepo-integration-tools."""

# the code below is json, so need to define a couple of aliases just to be sure
true = True
"""JSON True."""

false = False
"""JSON False."""

features_incorporated = '[{"name":"multipart-upload-from-5.11.1","base":"v5.11.1"}]'

oarepo_major_version = "12"

package_oarepo_version = "oarepo-5.11.1"

configuration = '{"name": "invenio-records-resources", "oarepo": 12, "features": [{"name": "multipart-upload-from-5.11.1", "base": "v5.11.1"}], "package": "invenio-records-resources", "invenio_version": "5.11.1", "version": "5.11.1"}'
